# mybatis的mapper配置文件
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.example.mybatisanddruid.mapper
  mapper-locations: classpath*:mapper/*.xml

spring:
  messages:
    basename: i18n/Messages, i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://CHDLXDB06:3306/tag
    username: mkbiz
    password: MaikeN2@41811
    dbcp2: # 数据库连接池的配置
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化提供的连接数
      max-total: 5 # 最大的链接数
      max-wait-millis: 200 # 等待链接获取的最大超时时间
debug: true
